name: Xaml Styler

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  xaml-styler:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 6.0.427
    - name: Install XAML Styler 
      run: dotnet tool update --global XamlStyler.Console
    - name: Verify XAML Styling
      run: xstyler -r -l Verbose -c src/xaml-styler.json -d "." --passive